import math

from scipy.interpolate import LinearNDInterpolator
import pandas as pd
import numpy as np

from .Controls import Controls
from Rocket import Rocket

class Canards(Controls):
    """
    Canards Control Object

    Attributes:
        airfoilDataPath (str): The path to a table of C_L for different velocities and AOA's
        root_m (float): Root coord of the canards in meters
        tip_m (float): Tip coord of the canards in meters
        span_m (float): Span of the canards in meters
        sweep_m (float): Sweep of the canards in meters
        numCanards (float): Number of canards
        offset_m (float): Distance from the center axis to the canards in meters
        maxAngle_dar (float): Max deflection angle of the canards in radians
        rateLimit_rps (float): Max angular speed of the canards in radians / sec
        updateFreq_hz (float): Update frequency of the canards in hz
        angle_rad (float): The canard current angle in radians
    """

    airfoilDataPath:    str
    _airfoilData:       pd.DataFrame
    _airfoilPoints:     list[float]
    _airfoilValues:     list[float]
    _liftInterpFunc:    any

    root_m:         float
    tip_m:          float
    span_m:         float
    sweep_m:        float
    _surfaceArea_m2: float

    numCanards: float
    offset_m:   float

    maxAngle_rad:   float
    rateLimit_rps:  float
    updateFreq_hz:  float


    _angle_rad:   float = 0.0
    dt:                 float = 0.0

    def __init__(self, airfoilDataPath: str, root_m: float, tip_m: float, span_m: float,
        sweep_m: float, numCanards: float, offset_m: float, maxAngle_deg: float, rateLimit_dps: float,
        updateFreq_hz: float
    ):
        """
        Initialize the Canards object

        Args:
            airfoilDataPath (str): The path to a table of C_L for different velocities and AOA's
            root_m (float): Root coord of the canards in meters
            tip_m (float): Tip coord of the canards in meters
            span_m (float): Span of the canards in meters
            sweep_m (float): Sweep of the canards in meters
            numCanards (float): Number of canards
            offset_m (float): Distance from the center axis to the canards in meters
            maxAngle_deg (float): Max deflection angle of the canards in degrees
            rateLimit_dps (float): Max angular speed of the canards in degrees / sec
            updateFreq_hz (float): Update frequency of the canards in hz
        """
        super().__init__("Canards")

        self.airfoilDataPath = airfoilDataPath
        self._airfoilData     = pd.read_csv(self.airfoilDataPath)
        self._airfoilPoints   = self._airfoilData[['alpha', 'Velocity']].values
        self._airfoilValues   = self._airfoilData['CL'].values
        self._liftInterpFunc = LinearNDInterpolator(self._airfoilPoints, self._airfoilValues, fill_value=0.0)

        self.root_m  = root_m
        self.tip_m   = tip_m
        self.span_m  = span_m
        self.sweep_m = sweep_m

        self._surfaceArea_m2 = (self.root_m + self.tip_m) / 2 * self.span_m

        self.numCanards    = numCanards
        self.offset_m      = offset_m
        self.maxAngle_rad  = math.radians(maxAngle_deg)
        self.rateLimit_rps = math.radians(rateLimit_dps)
        self.updateFreq_hz = updateFreq_hz

        # Init default values
        self._angle_rad = 0.0
        self._dt = 0.0

    @property
    def angle_rad(self) -> float:
        return self._angle_rad

    @angle_rad.setter
    def angle_rad(self, angle):
        maxChange = self.rateLimit_rps * self._dt # Calculate the max rate of change

        self.angleRate_rps = angle - self._angle_rad # Calculate the target rate of change
        self.angleRate_rps = max(-maxChange, min(maxChange, self.angleRate_rps)) # Clamp the rate of change
        self._angle_rad += self.angleRate_rps

        self._angle_rad = max(min(self._angle_rad, self.maxAngle_rad), -self.maxAngle_rad) # Clamp output

    def sim(self, rocket: Rocket, **kwargs) -> tuple[float, float, float]:
        """
        Simulate the canards

        Args:
            dt (float): The change in time since the last step in seconds

        Raises:
            TypeError

        Returns:
            tuple[float, float, float]: Tuple of toques generated by the control [yaw, pitch, roll] in Nm
        """

        if not ("canardAngle_deg" in kwargs.keys()):
            raise TypeError("missing 1 required positional argument: 'canardAngle_deg'")

        self.angle_rad = math.radians(kwargs['canardAngle_deg'])
        self._dt = rocket.simTimeStep

        generatedTorque_Nm  = self.__calculateFinLift(rocket) * self.offset_m
        generatedTorque_Nm *= -1 if self.angle_rad < 0 else 1
        generatedTorque_Nm *= self.numCanards

        return (0.0, 0.0, generatedTorque_Nm)

    def __calculateFinLift(self, rocket: Rocket) -> float:
        """
        Calculate the lift of the canard for the current AOA and rocket vertical velocity

        Args:
            rocket (Rocket): The rocket that this is attached to

        Returns:
            float: The lift generated by the canard
        """

        cl = self._liftInterpFunc(abs(math.degrees(self._angle_rad)), rocket.zVel_mps)
        cl = float(cl) if not np.isnan(cl) else math.nan

        if cl == "Out of bounds":
            # print(f"Warning: Angle {math.degrees(angle):.2f} degrees and velocity {airspeed:.2f} m/s are out of bounds for the CL interpolator.")
            # If the angle and velocity are outside the range of the CSV, we can assume the coefficient of lift is 0
            #   Its either a low AOA or slow speed, its an assumption that may or maynot hold up
            return 0
        
        generatedLift = cl * 0.5 * rocket.zVel_mps**2 * rocket.airDensity * self._surfaceArea_m2

        return generatedLift

    @property
    def angle_deg(self) -> float:
        return math.degrees(self._angle_rad)

