from Rocket import Rocket

class Controls:
    """
    Abstract base class for all rocket control methods (e.g. Canards,
    ReactionWheel).

    A Controls object is polled once per simulation step by `Rocket.sim()`,
    which calls `sim(rocket=self, **kwargs)` on every control in
    `Rocket.controls` and sums the returned torque tuples across all of
    them. Subclasses must override `sim()` to compute and return their own
    torque contribution; the base implementation always raises
    NotImplementedError.

    To add a new control mechanism:
        1. Subclass `Controls` and call `super().__init__(<controlType>)`.
        2. Override `sim(self, rocket: Rocket, **kwargs)` to return a
           `(yawTorque_Nm, pitchTorque_Nm, rollTorque_Nm)` tuple.
        3. Accept whatever control-specific keyword arguments you need via
           `**kwargs` (e.g. `Canards` expects `canardAngle_deg`) — these are
           passed through unchanged from whatever the caller passes into
           `Rocket.sim(**kwargs)`.

    Raises:
        NotImplementedError: When `sim()` isn't overridden by the child object.

    Attributes:
        controlType (str): The name of the control type ex. Canards, ReactionWheel, etc.
    """

    controlType: str = "Base"

    def __init__(self, controlType: str):
        """
        Initialize a control object.

        Args:
            controlType (str): The name of the control type ex. Canards, ReactionWheel, etc.
        """
        self.controlType = controlType

    def sim(self, rocket: Rocket, **kwargs) -> tuple[float, float, float]:
        """
        Compute this control's torque contribution for the current step.

        Must be overridden by subclasses; this base implementation always
        raises NotImplementedError. Subclasses should use `rocket`'s
        current state (e.g. `rocket.zVel_mps`, `rocket.simTimeStep`,
        `rocket.airDensity`) and any control-specific values passed via
        `**kwargs` to compute the torque this control generates this step.

        Args:
            rocket (Rocket): The rocket this control is attached to, giving
                access to current state such as velocity, air density, and
                `simTimeStep`.
            **kwargs: Control-specific keyword arguments forwarded from
                `Rocket.sim(**kwargs)` (e.g. `Canards` requires
                `canardAngle_deg`).

        Raises:
            NotImplementedError: Always, unless overridden by a subclass.

        Returns:
            tuple[float, float, float]: Tuple of torques generated by the
                control as (yawTorque_Nm, pitchTorque_Nm, rollTorque_Nm).
        """

        raise NotImplementedError(f"Please implement the sim function in {self.controlType}")