from Rocket import Rocket

class Controls:
    """
    Base class for all control methods

    Raises:
        NotImplementedError: When the sim function isn't overridden by the child object

    Attributes:
        controlType (str): The name of the control type ex. Canards, ReactionWheel, etc.
    """

    controlType: str = "Base"

    def __init__(self, controlType: str):
        """
        Initialize a control object.

        Args:
            controlType (str): The name of the control type ex. Canards, ReactionWheel, etc.
        """
        self.controlType = controlType

    def sim(self, rocket: Rocket, **kwargs) -> tuple[float, float, float]:
        """
        Simulate the control object

        Args:
            dt (float): The change in time since the last step in seconds

        Returns:
            tuple[float, float, float]: Tuple of toques generated by the control [yaw, pitch, roll] in Nm
        """

        raise NotImplementedError(f"Please implement the sim function in {self.controlType}")
        return (0.0, 0.0, 0.0)